"""
    企业知识库问答系统（LangChain 1.0）

    功能：
    - 文档批量导入
    - 智能分块
    - 向量检索
    - RAG 问答
    - 答案溯源
"""

from datetime import datetime
import json
import os

from dotenv import load_dotenv
from langchain.chat_models import init_chat_model
from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_community.vectorstores import FAISS
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_openai import OpenAIEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter


load_dotenv()

class KnowledgeBase:
    """企业知识库系统"""

    def __init__(
        self,
        docs_directory: str = "./knowledge_docs",
        index_directory: str = "./knowledge_index",
        embedding_model: str = "text-embedding-v4"
    ):
        self.docs_directory = docs_directory
        self.index_directory = index_directory

        # 初始化 Embedding
        print("初始化 Embedding模型...")
        self.embeddings = OpenAIEmbeddings(
            base_url= "https://dashscope.aliyuncs.com/compatible-mode/v1",
            api_key=os.getenv("OPENAI_API_KEY") or os.getenv("DASHSCOPE_API_KEY"),
            model="text-embedding-v4",
            # DashScope accepts text strings, not the token arrays generated by
            # LangChain's default context-length check.
            check_embedding_ctx_length=False,
        )

        print(" Embedding模型初始化完成！")

        # 文本分块器
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=500,
            chunk_overlap=50,
            separators=["\n\n", "\n", "！", "。", "？", "；", "，", " ", ""]
        )

        # 向量数据库
        self.vectorstore = None

        # LLM
        self.model = init_chat_model(
            model="qwen-plus",
            model_provider="openai",
            base_url= "https://dashscope.aliyuncs.com/compatible-mode/v1",
            api_key=os.getenv("DASHSCOPE_API_KEY") or os.getenv("OPENAI_API_KEY"),
            temperature=0.0,
        )

        # 查询历史
        self.query_log = []

    def build_index(self):
        """构建索引"""
        print("开始构建索引...")

        # 1.加载文档
        print("\n 正在加载文档")
        loader = DirectoryLoader(
            self.docs_directory,
            glob="**/*.txt",
            loader_cls=TextLoader,
            loader_kwargs={"encoding": "utf-8"},
            show_progress=True
        )

        try:
            docs = loader.load()
            print(f"加载的文档数量：{len(docs)}")
        except Exception as e:
            print(f"加载文档时出错：{e}")
            return False

        if not docs:
            print("没有找到文档，请确保文档目录下有 .txt 文件")
            return False

        # 2.文本分块
        print("\n 正在分块文档")
        split_docs = self.text_splitter.split_documents(docs)
        print(f"分块完成，共生成 {len(split_docs)} 个块")

        # 3.创建向量数据库
        print("正在创建向量化并建立索引...")
        self.vectorstore = FAISS.from_documents(split_docs, self.embeddings)
        self.vectorstore.save_local(self.index_directory)
        print(f"索引已保存到 {self.index_directory}")

        return True

    def load_index(self):
        """加载已有索引"""
        print("正在加载索引...")
        try:
            self.vectorstore = FAISS.load_local(
                self.index_directory,
                self.embeddings,
                allow_dangerous_deserialization=True
            )
            print("索引加载成功")
            return True
        except Exception as e:
            print(f"加载索引时出错：{e}")
            return False

    def query(self, question: str, k: int = 3) -> dict:
        """查询数据库"""
        if not self.vectorstore:
            return {"error": "知识库未初始化"}

        # 1.检索相关文档
        retriever = self.vectorstore.as_retriever(
            search_type="similarity",
            search_kwargs={"k": k}
        )

        docs = retriever.invoke(question)

        # 2.构建提示词
        prompt = ChatPromptTemplate.from_template(
            """

            你是企业知识库问答助手。

            请给予以下文档回答问题

            文档片段：
            {context}

            用户问题：
            {question}

            回答要求：
            1.仅基于提供的文档内容回答，不要编造信息
            2.如果上下文没有相关信息，明确告诉用户
            3.回答要准确、完整、易懂
            4.如果答案来自多个文档片段，请综合回答

            答案：
            """
        )

        # 3.格式化文档
        def format_docs(docs):
            return "\n\n---\n\n".join([
                f"【文档 {i+1}】\n来源：{doc.metadata.get('source', '未知')}\n内容：{doc.page_content}"
                for i, doc in enumerate(docs)
            ])

        # 4.构建RAG Chain
        rag_chain = (
            {"context": lambda _: format_docs(docs), "question": RunnablePassthrough()}
            | prompt
            | self.model
            | StrOutputParser()
        )

        # 5.生成答案
        answer = rag_chain.invoke(question)

        # 6.记录查询
        self.query_log.append({
            "question": question,
            "answer": answer,
            "sources": [doc.metadata.get('source', '未知') for doc in docs],
            "timestamp": datetime.now().isoformat()
        })

        return {
            "question": question,
            "answer": answer,
            "sources": docs,
            "source_count": len(docs),
        }

    def export_logs(self, filename: str = "query_log.json"):
        """导出查询日志"""
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(self.query_log, f, ensure_ascii=False, indent=2)
        print(f"查询日志已保存至 {filename}")

def create_sample_docs(directory: str = "./knowledge_docs"):
    """创建示例文档"""
    os.makedirs(directory, exist_ok=True)

    docs = {
        "company_intro.txt": 
        """
        公司简介：

        我们是一家提供 AI 服务的公司。
        我们拥有many years的AI经验。
        我们提供many services，如机器学习、深度学习、自然语言处理、图像识别等等。

        主要产品：
        1. AI开发平台
        2. 智能客服系统
        3. 知识库问答系统

        联系方式：
        地址：中国上海
        电话：+86 1234567890
        邮箱：<EMAIL>

        团队介绍：
        1. 团队成员1：张三，负责机器学习
        2. 团队成员2：李四，负责深度学习
        3. 团队成员3：王五，负责自然语言处理
        4. 团队成员4：赵六，负责图像识别

        
        功能特性：
        1. 提供机器学习、深度学习、自然语言处理、图像识别等功能
        2. 支持多种编程语言，如Python、Java、C++、JavaScript等等
        3. 支持多种数据库，如MySQL、PostgreSQL、MongoDB等等
        4. 支持多种平台，如Windows、Linux、MacOS等等
        5. 支持多种设备，如PC、手机、平板等等
        6. 支持多种浏览器，如Chrome、Firefox、Safari等等
        7. 支持多种操作系统，如Windows、Linux、MacOS等等

        技术优势：
        1. 团队成员拥有many years的AI经验，能够提供many services
        2. 团队成员使用many popular libraries，如TensorFlow、PyTorch、Keras、Scikit-learn等等
        3. 团队成员使用many popular databases，如MySQL、PostgreSQL、MongoDB等等
        4. 团队成员使用many popular platforms，如Django、Flask、Spring Boot等等
        5. 团队成员使用many popular devices，如PC、手机、平板等等

        核心功能：
        1. 多轮对话
        2. 智能推荐
        3. 智能搜索
        4. 智能问答
        5. 智能推荐
        6. 智能翻译
        7. 智能生成
        8. 智能计算

        适用场景：
        1. 智能助手
        2. 知识库问答
        3. 智能客服
        4. 智能推荐
        5. 智能翻译
        6. 智能生成

        接入方式：
        1. 通过API接入
        2. 通过SDK接入
        3. 通过Docker接入
        4. 通过Kubernetes接入
        5. 通过Helm Chart接入
        6. 通过Ansible接入
        7. 通过Terraform接入
        8. 通过CloudFormation接入
        9. 通过AWS Lambda接入
        10. 通过Azure Function接入
        11. 通过Google Cloud Function接入
        12. 通过阿里云 Function Compute接入

        """,
    }

    for filename, content in docs.items():
        filepath = os.path.join(directory, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    print(f"已创建 {len(docs)} 个示例文档 到 {directory}")


def main():
    """主程序"""
    print("="*80)
    print("企业知识库问答系统（Langchain 1.0）")
    print(f"当前时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*80)

    kb = KnowledgeBase()

    # 检查是否有已存在的索引
    if os.path.exists(kb.index_directory):
        print("\n 发现已有的索引")
        answer = input("是否使用已有索引？(y/n) ：").strip().lower()
        if answer == "y":
            if not kb.load_index():
                print("索引加载失败，请重新创建索引")
                create_sample_docs()
                kb.build_index()
        else:
            create_sample_docs()
            kb.build_index()
    else:
        print("\n 未发现已存在的索引，开始创建索引")
        create_sample_docs()
        if not kb.build_index():
            print("索引创建失败，程序退出")
            return

    # 示例查询
    print("\n" + "="*80)
    print("示例查询：")
    print("=" * 80)

    test_questions = [
        "公司简介",
        "团队介绍",
        "技术优势",
        "核心功能",
        "适用场景",
        "接入方式",
        "公司主要产品有哪些？"
    ]

    for question in test_questions:
        print(f"\n问题：{question}")
        result = kb.query(question)

        print(f"{result['question']} -> {result['answer']}")
        print(
            "参考文档："
            + ", ".join(doc.metadata.get("source", "未知") for doc in result["sources"])
        )
        print("=" * 80)

    # 交互模式
    print("\n" + "="*80)
    print("交互模式（输入quit退出，输入export导出日志）")
    print("=" * 80)

    while True:
        question = input("\n请输入问题：").strip()

        if question.lower() == 'quit':
            kb.export_logs()
            print("再见！")
            break

        if question.lower() == 'export':
            kb.export_logs()
            continue

        if not question:
            continue

        result = kb.query(question)

        print(f"\n 答案：\n {result['answer']}")
        print(f"参考来源：")
        for i, doc in enumerate(result['sources'], 1):
            print(f"    {i}. {doc['source']}")
            print(f"      内容片段：{doc.page_content[:100]}")

if __name__ == "__main__":
    main()
